language: node_js
sudo: required
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- polylint
node_js: stable
addons:
  firefox: '46.0'
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  sauce_connect: true
script:
- xvfb-run wct
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s 'default'; fi
SAUCE_USERNAME=polymer-ci:
  secure: MdclMoQBh7FSa11Mfw1Q7Gx5dYmsfHp5w3tSj5i798eMsrDrHIbmJwnYAIEHch4wpIteQL4dynfzWyfpU3S1WSCTR7vNsbzz8XlmT+t+Bk474XOsKQ/I+z1Fd3NMSNR73H/rJxH3nEJfDSR6TFKfoT/SAO0/yPE1taSvvYJV3dRD6A+ZrftgDzaDB3YukiE+OU4Hsk0Fy8JnF3Lb5iAl9jkd8G5i0IfYpcXJwlPq3C9krs7i/QhVCa/PI2TQNubihGnQc9oSVYxU4BV2oJ7JvEgPYLc21jL07c71Mr7Nl7ZCxnGqPYHxtwFMalBaenHg+CdnReOyh3CjbPhK/c0avX9Xgnpsex2pt3gXo98sZ0TBCfsEm/eKPpzxktAs2XwQXV3Xct1t8Oop4tbwUqgobXOSR3GM/YY8+FONr7D4NENtMiarujvywfhUK4dwc5sSY44uEocEUoYfcNEO3YAu0TyGhtjlTkhRscW6W10ASnLHQ3Vkg1/OOwBiQC1OSZHudffc11yY6rQGlD7K48n2TIu8yI8m2AyEXWxTF6XINCC80+rSNJEibiih1McGbwqACv71S6fBhCNdS2UXfO8MWDe6Lg7TgFXfLqkLRuNz+YR/Jpp9Kx5JgdDLbDvddSaOZII5WUcP+CjAwe+dOHXxuiIao18Y1AUs1K49zShukN8=
env:
  global:
  - secure: eScrrC6Ki856GHdqjjuEgjbY4uVA2AtF19Su0Z7Ynnxe34LZffPA835BrImQhqApgXjd85xJBcWB+YbmgDA068cLm8WiQK3D4b8xWFgGd/TxzoBZpvHvvkZ4gH4Z4aj0mwMrFI4iTMGoIwxG40+W3tU0R1HpDDKnskHU7xlpWW1LFRUpUw+uizikUrCmJ5/EsGJ3ti1mzx9p2tm7KRog436dAXJek8M+WsBtqqxHnYqqsat4y0TxHg7MKyzs/ZT5683cYo84iQZvyz3WdRTGDMCPKjDrldfunwSkakygr7s+SAkUUomAFdVdV7OYhQRWGXS4ey1SCRJrklCrX8U4BwW0wizw1BhAivVR6Ab+628nx3uGpajPyXg6gRRsr9/q9+StHcUIAEhnjcpByICzFn3fht5KYJtPBIaUfxwxTHvDmjhcFv10K7zM2Mc1jPA14c71dXtkOQLMEpG14PT0UV/JgY931bzoeoPtYeO09zOP+EKAcLq1DQI6I66UIqJLitjr2W6UqZt8Ei1sI7bR5Tce1jHw/MRCH38SKy69BTtKzUs/Z2/+GlSIqDKw2Fp5RB5l0JrhYvy5Pwb6E7Ds0kIiFe6xmvjB/XjAH15Hxt76bc20CX3O+IXFAwDSnhiTjSHUo78ku6WbeGYHpdYizCQdJNCPukpXMxyNMAUg6v8=
  - secure: gE2pkjfJWdDZ/Oi8Ns0H90qUXiIDowRVjbnrJp3y5ARfA/3xM90gcClYKd7xZsYNInNwNzom2ZLxI5BZjg8UDFNmzhWdVwbiB3kGEQ82sfgTSbNDcjzp+FF6Qgz2tVuxOpHuTTcYXip96BgB9jHG7Ovv7GZf5ms4MOvW0KE/mCxSxO5a5hl9LsB2df2HnKnAU9pIMqsv9DkzVDx45O9S5CQ2LE63ZcWIuwPly1Mgv/M+Z5B6A+Vo/003yWni92WtYDcIkzhKSXQkfUvONL09udtaMHUk/5T8tgEhxxEQxhVGJrulZ6CBPZei1eELlt5ebM1MimHDLc/Cyl8QNY7kK35lqU247/1PkbsCoZdvb7aCjWhNPJJ9Io9VXu1pW/l5rBM2VIuGcTDpcJ6RltYnIeg+EWGq5POj/wEu0BbL4IbCKibW2VacvTFa7SRtJzCwHQ1w8H1MxJsxs+2BtCZ/PaGb7nMViwaD1sPMspHY6xtfu9urVGtgmaIbMLYRvMQS6zWrdAZcmAQ3opJnsmgp4Nku+FV4yUupQHmWbwX+eoaqJiDr+h8/5T3MrvlSyL3zpDSVaQJF2Aarv/hLsf9zZbWUXbhHnS2JaLIcIQsRUOloUn5Gt+70iGszdFnfRoxo1aUTaOY2DMwBwiewRd9z76KsVJLEOUmZzFXt0V7VgkQ=
dist: trusty
